### ISSUE TITLE
Code samples

### ISSUE THREAD

**Issue by suriyaa** [shiroyasha/bracket#7]
@shiroyasha: Do you have any code examples for this programming language?

**Comment by shiroyasha** [comment]
No :) But it should be dead simple lisp like language (it was a weekend side project a year ago).

The following example should work:

```
(+ 1 2 (/ 4 5))
```

**Comment by SuriyaaKudoIsc** [comment]
Other examples?

**Comment by suriyaa** [comment]
@shiroyasha: Thank you for your support!
